### ISSUE TITLE
Spanish translate

### ISSUE THREAD

**Issue by TheJayGamer** [if-Team/ModPE-Scripts#10]
1. Trade : Vender
2. Buy : Comprar
3. Sell : Comprar
4. About : Acerca de
   5 .Check Update : Analizar Actualizaciones 
5. Special Thanks to : Gracias a:
6. Update! : ~~ Nueva Actualization!!
7. New version of TradePE has been found! Will you install it now? : ~~ Nueva version de TradePE encontrada! Desea actualizar?
8. Later : ~~ Despues...
9. Not Enough Items : ~~ No Tienes suficientes Items.
   11.Not Enough Emeralds : ~~ No tienes suficientes Esmeraldas
   [TheJay!]

**Comment by TheJayGamer** [comment]
Is spanish

**Comment by chalkpe** [comment]
Thanks, but can you write it on #9 with a new form?

**Comment by chalkpe** [comment]
And... what is different from @TaQuIt0's Spanish translation?
