### ISSUE TITLE
Chinese translation by@jnjnnjzch

### ISSUE THREAD

**Issue by jnjnnjzch** [if-Team/ModPE-Scripts#11]
# zh_CN by @jnjnnjzch

| Original | Translation |
| :-- | :-- |
| `Trade` | `交易` |
| `Buy` | `购买` |
| `Sell` | `出售` |
| `About` | `关于` |
| `Check for updates` | `检查更新` |
| `Special thanks to` | `特别感谢` |
| `Update!` | `有更新！` |
| `A new version of TradePE has been found!` | `发现新版本！` |
| `Would you like to install it now?` | `立即下载？` |
| `Later` | `稍后` |
| `Not enough items` | `物品不足` |
| `Not enough emeralds` | `绿宝石不足` |

**Comment by chalkpe** [comment]
#9
