### ISSUE TITLE
Please help our translations of TradePE!

### ISSUE THREAD

**Issue by jaehee0507** [if-Team/ModPE-Scripts#9]
Hi, guys. I need your help to translate TradePE. I am planning to make it support MultiLang.

If you want to help me, comment the translation!

The form is,

```
# en_US by @anonymous
Original | Translation
:------- | :-------
`Trade` | `?`
`Buy` | `?`
`Sell` | `?`
`Info` | `?`
`Check for updates` | `?`
`Special thanks to` | `?`
`Update!` | `?`
`A new version of TradePE has been found!` | `?`
`Would you like to install it now?` | `?`
`Later` | `?`
`Not enough items` | `?`
`Not enough emeralds` | `?`
```

**Comment by jaehee0507** [comment]
For example,

# ko_KR by @affogatoman

| Original | Translation |
| :-- | :-- |
| `Trade` | `거래하기` |
| `Buy` | `구입` |
| `Sell` | `판매` |
| `Info` | `정보` |
| `Check for updates` | `업데이트 확인` |
| `Special thanks to` | `도와주신 분들` |
| `Update!` | `업데이트!` |
| `A new version of TradePE has been found!` | `TradePE의 새 버전을 발견했습니다!` |
| `Would you like to install it now?` | `지금 바로 설치하시겠습니까?` |
| `Later` | `나중에` |
| `Not enough items` | `아이템이 부족합니다` |
| `Not enough emeralds` | `에메랄드가 부족합니다` |

**Comment by Desno365** [comment]
Hi. 
I'm not English but I'm pretty sure that, for more correctness, you should change `New version was found` to `A new version has been found` and `New version of TradePE was found! Will you install it now?` to `A new version of TradePE has been found! Would you like to install it now?`.  

Now some Italian translations for you:
1. Scambia
2. Compra
3. Vendi
4. A riguardo
5. Controlla aggiornamenti
6. Ringraziamenti speciali per
7. Una nuova versione è stata trovata! 
8. Una nuova versione di TradePE è stata trovata! Vuoi installarla ora? 
9. Sì 
10. Più avanti
11. Non hai abbastanza oggetti
12. Non hai abbastanza Smeraldi

**Comment by jaehee0507** [comment]
@Desno365 Thanks for feedback and translation!!

**Comment by TaQuIt0** [comment]
Español
1. Trade : Comerciar
2. Buy : Comprar
3. Sell : Vender
4. About : Acerca de 
   5 .Check Update : Buscar Actualización 
5. Special Thanks to : Agradecimiento Especial Para
6. Update! : Actualizacion!
7. New version of TradePE has been found! Will you install it now? : Una nueva versión de TradePE ha sido encontrada! Quieres instalar ahora?
8. Later : Despues
9. Not Enough Items : No Hay Items suficientes
   11.Not Enough Emeralds : No Hay Esmeraldas Suficientes

@TaQuItO_988

**Comment by rekmolly** [comment]
RU - Russia
1. Trade : Торговля
2. Buy : Купить
3. Sell : Продать
4. About : Информация
   5 .Check Update : Проверить обновления
5. Special Thanks to : Особая благодарность
6. Update! : Обновление!
7. New version of TradePE has been found! Will you install it now? : Была найдена новая версия TradePE! Установить сейчас?
8. Later : Позже
9. Not Enough Items : Не хватает предметов
   11.Not Enough Emeralds : Не хватает изумрудов
   12.Yes - Да

**Comment by chalkpe** [comment]
Oops, this form is out of date!

**Comment by chalkpe** [comment]
Well, I updated the new form!

**Comment by Maluquinho** [comment]
1.Trade : Comércio
2.Buy:  Comprar
3.Sell: Vender
4. About:    ????? 
5.Check for updates: Ver se há Atualizaçōes
6.Special thanks to:    Agradecimentos Para Maluquinho
7.Update!:  Atualização!
8.A new version of TradePE has been found! :  Uma nova versão de TradePE está disponivel
9.Would you like to install it now?: Voce quer instalar agora? 
10.Later: Depois
11.Not enough items : Voce não Tem items
12.Not enough emeralds: Voce não tem esmeraldas

```
             Language:PT_BR

                        :P
```

**Comment by Maluquinho** [comment]
Hey!!!! About is:
Acerca de

**Comment by jnjnnjzch** [comment]
# zh_CN by @jnjnnjzch

| Original | Translation |
| :-- | :-- |
| `Trade` | `交易` |
| `Buy` | `购买` |
| `Sell` | `出售` |
| `About` | `关于` |
| `Check for updates` | `检查更新` |
| `Special thanks to` | `特别感谢` |
| `Update!` | `有更新！` |
| `A new version of TradePE has been found!` | `发现TradePE的新版本！` |
| `Would you like to install it now?` | `立即下载？` |
| `Later` | `稍后` |
| `Not enough items` | `物品不足` |
| `Not enough emeralds` | `绿宝石不足` |

**Comment by mkmkjip** [comment]
Japanese/日本語
1.Trade : トレード
2.Buy: 購入
3.Sell: 売却
4.About (this mod): (このモッド)について 
5.Check for updates: アップデートのチェック
6.Special thanks to: スペシャルサンクス
7.Update!: アップデート！
8.A new version of TradePE has been found! : 新しいバージョンが見つかりました
9.Would you like to install it now?: 今すぐアップデートしますか？
10.Later: あとで
11.Not enough items : アイテムが足りません
12.Not enough emeralds: エメラルドが足りません

**Comment by AdrianBlz20** [comment]
French translation :)

Trade: Commerce
Buy: Acheter
Sell: Vendre
About: Environ
Check for updates: Vérifier les mises à jour
Special thanks to: merci spécial à
Uptade! : Mise à jour!
A new version of TradePE has been found! : Une nouvelle de TradePE a été trouvé!
Would you like to install it now? : Souhaitez-vouz l'installer maintenant?
Later: Plus tard
Not enough items : Pas assez d'éléments
Not enough emeralds: Pass assez émeraudes

**Comment by peacestorm** [comment]
# nl_NL by @peacestorm

| Original | Translation |
| :-- | :-- |
| `Trade` | `Ruil` |
| `Buy` | `Koop` |
| `Sell` | `Verkoop` |
| `Info` | `Info` |
| `Check for updates` | `Zoeken naar updates` |
| `Special thanks to` | `Met dank aan` |
| `Update!` | `Update!` |
| `A new version of TradePE has been found!` | `Er is een nieuwe versie van TradePE beschikbaar!` |
| `Would you like to install it now?` | `Wil je het nu meteen installeren?` |
| `Later` | `Later` |
| `Not enough items` | `Niet genoeg items` |
| `Not enough emeralds` | `Niet genoeg smaragden` |

**Comment by Maluquinho** [comment]
# pt_BR by @eu_sozin

Translation (New)
Trade  Comércio
Buy  Comprar
Sell     Vender
Info     Informação
Check for updates  Ver se há Atualizaçōes
Special thanks to  Agradecimentos para
Update!     Atualização!
A new version of TradePE has been found!  Uma nova versão de TradePE foi encontrada
Would you like to install it now?  Voce quer instalar agora? 
Later  Depois
Not enough items  Não tem items suficientes
Not enough emeralds     Não tem esmeraldas suficientes

**Comment by chalkpe** [comment]
Wow, thanks to all :)

**Comment by jnjnnjzch** [comment]
# zh_CN by @jnjnnjzch

| Original | Translation |
| :-- | :-- |
| `Trade` | `交易` |
| `Buy` | `购买` |
| `Sell` | `出售` |
| `Info` | `信息` |
| `Check for updates` | `检查更新` |
| `Special thanks to` | `特别鸣谢` |
| `Update!` | `立即更新！` |
| `A new version of TradePE has been found!` | `发现TradePE的新版本！` |
| `Would you like to install it now?` | `是否立即下载？` |
| `Later` | `稍后再说` |
| `Not enough items` | `交易物品不足` |
| `Not enough emeralds` | `绿宝石不足` |

**Comment by sero583** [comment]
German #de_DE @sero583 (My Twitter is @serhat50014 and at Twitter my name Serhat Güler)

| Original | Translation |
| :-- | :-- |
| `Trade` | `Tauschen` |
| `Buy` | `Kaufen` |
| `Sell` | `Verkaufen` |
| `Info` | `Info` |
| `Check for updates` | `Suche nach Updates` |
| `Special thanks to` | `Besonderen Dank an` |
| `Update!` | `Aktualisierung` |
| `A new version of TradePE has been found!` | `Eine neue Version von TradePE wurde gefunden!` |
| `Would you like to install it now?` | `Willst du es jetzt installieren?` |
| `Later` | `Später` |
| `Not enough items` | `Nicht genug Items` |
| `Not enough emeralds` | `Nicht genug Smaragd` |

**Comment by jnjnnjzch** [comment]
# zh_CN by @jnjnnjzch

| Original | Translation |
| :-- | :-- |
| `Trade` | `交易` |
| `Buy` | `购买` |
| `Sell` | `出售` |
| `Info` | `信息` |
| `Check for updates` | `检查更新` |
| `Special thanks to` | `特别鸣谢` |
| `Update!` | `有更新！` |
| `A new version of TradePE has been found!` | `发现新版本！` |
| `Would you like to install it now?` | `是否立即下载？` |
| `Later` | `稍后再说` |
| `Not enough items` | `物品不足` |
| `Not enough emeralds` | `绿宝石不足` |
